# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['input_body_parameters', 'calculate_bmr']

# Cell
def input_body_parameters(message_dict):
    body_params = {}
    for param in message_dict.keys():
        body_params[param] = int(input(message_dict[param]))
        #assert isinstance(body_params[param], int), 'Input variables should be integers'
        assert body_params[param] > 0, 'Only positive numbers are allowed'
    return body_params

def calculate_bmr(body_parameters, gender):
    if gender == 'w':
        bmr = float(655.1 + (9.563 * body_parameters['weight']) +
         (1.850 * body_parameters['height']) -
         (4.676 * body_parameters['age']))
    elif gender == 'm':
        bmr = float(66.47 + (13.75 * body_parameters['weight']) +
        (5.003 * body_parameters['height']) -
        (6.755 * body_parameters['age']))
    print(f'Your BMR is {bmr:.1f} \n')
    return bmr